# name: Deploy to Firebase Hosting
# on:
#   push:
#     branches:
#       - master
# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Setup Flutter
#         uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.27.x"
#           channel: "stable"
#           cache: true

#       - name: Clean old builds
#         run: |
#           rm -rf build/
#           rm -rf .dart_tool/
#           rm -rf .flutter-plugins
#           rm -rf .flutter-plugins-dependencies

#       - name: Get dependencies
#         run: |
#           flutter clean
#           flutter pub get

#       - name: Enable web
#         run: flutter config --enable-web

#       - name: Build web
#         run: flutter build web --release

#       - name: Deploy to Firebase
#         uses: FirebaseExtended/action-hosting-deploy@v0
#         with:
#           repoToken: "${{ secrets.GITHUB_TOKEN }}"
#           firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_HAPPY_DEALS_3F03D }}"
#           channelId: live
#           projectId: happy-deals-3f03d
