name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      
      - name: Enable Flutter Web
        run: flutter config --enable-web
        
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build Flutter Web
        run: flutter build web --release
        
      - name: Remove base href
        run: |
          sed -i 's/<base href="\/"\s*\/?>//g' build/web/index.html
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
