name: Deploy Flutter Web to GitHub Pages
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: Enable Flutter Web
        run: flutter config --enable-web
      - name: Get dependencies
        run: flutter pub get
      - name: Build Flutter Web
        run: flutter build web --base-href "/happydeals/"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Update base href in index.html
        run: |
          sed -i 's/<base href="\/happydeals\/">/<base href="\/happydeals\/#\/">/' index.html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update base href in index.html"
          git push
